package dev.carnager.noterious.ui

import dev.carnager.noterious.model.ServerMetaResponse
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.time.Instant

@Serializable
private data class BackupManifestDocument(
    val generatedAt: String,
    val app: BackupManifestApp,
    val paths: BackupManifestPaths,
    val restartRequired: Boolean,
    val notes: List<String>,
)

@Serializable
private data class BackupManifestApp(
    val name: String,
    val listenAddr: String,
)

@Serializable
private data class BackupManifestPaths(
    val vaultRoot: String,
    val dataDir: String,
    val database: String,
    val currentScopeVault: String? = null,
)

private val backupManifestJson = Json {
    prettyPrint = true
    explicitNulls = false
}

internal fun backupManifestFilename(meta: ServerMetaResponse): String {
    return "noterious-backup-manifest-${safeTimestamp(meta.serverTime)}.json"
}

internal fun buildBackupManifest(meta: ServerMetaResponse): String {
    val runtimeVaultPath = safeString(meta.runtimeVault.vaultPath, "(unknown)")
    val currentScopeVault = safeString(meta.currentVault?.vaultPath)
    val document = BackupManifestDocument(
        generatedAt = safeString(meta.serverTime, Instant.now().toString()),
        app = BackupManifestApp(
            name = safeString(meta.name, "Noterious"),
            listenAddr = safeString(meta.listenAddr, "(unknown)"),
        ),
        paths = BackupManifestPaths(
            vaultRoot = runtimeVaultPath,
            dataDir = safeString(meta.dataDir, "(unknown)"),
            database = safeString(meta.database, "(unknown)"),
            currentScopeVault = currentScopeVault.takeIf { it.isNotBlank() && it != runtimeVaultPath },
        ),
        restartRequired = meta.restartRequired,
        notes = listOf(
            "Back up the full vault root and the full data dir together.",
            "The SQLite index database is rebuildable from the vault, but history, trash, themes, and auth state live under the data dir.",
            "Restore by stopping the server, restoring vault + data dir, then starting the server again.",
        ),
    )
    return backupManifestJson.encodeToString(document) + "\n"
}

internal fun backupScriptFilename(meta: ServerMetaResponse): String {
    return "noterious-backup-${safeTimestamp(meta.serverTime)}.sh"
}

internal fun buildBackupScript(meta: ServerMetaResponse): String {
    val appName = safeString(meta.name, "noterious")
    val generatedAt = safeString(meta.serverTime, Instant.now().toString())
    val runtimeVaultPath = safeString(meta.runtimeVault.vaultPath, "/path/to/noterious-vault")
    val dataDir = safeString(meta.dataDir, "/path/to/noterious-data")
    val database = safeString(
        meta.database,
        dataDir.trimEnd('/') + "/index.sqlite",
    )
    val currentScopeVault = safeString(meta.currentVault?.vaultPath)

    val lines = listOfNotNull(
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        comment("Generated by Noterious on $generatedAt."),
        comment("Usage: sh ./noterious-backup.sh [/path/to/backup-root]"),
        comment("This backs up the full deployment: runtime vault root + data dir."),
        comment("The SQLite index is rebuildable, but the rest of the data dir is not."),
        currentScopeVault.takeIf { it.isNotBlank() && it != runtimeVaultPath }
            ?.let { comment("Current UI scope at generation time: $it") },
        "",
        "APP_NAME=${shellQuote(appName)}",
        "VAULT_PATH=${shellQuote(runtimeVaultPath)}",
        "DATA_DIR=${shellQuote(dataDir)}",
        "DATABASE_PATH=${shellQuote(database)}",
        "",
        "BACKUP_ROOT=./noterious-backups",
        "if [ \"\$#\" -ge 1 ]; then",
        "  BACKUP_ROOT=\"\$1\"",
        "fi",
        "",
        "STAMP=\"\$(date -u +%Y%m%dT%H%M%SZ)\"",
        "TARGET_DIR=\"\$BACKUP_ROOT/\$APP_NAME-\$STAMP\"",
        "",
        "mkdir -p \"\$TARGET_DIR\"",
        "",
        "tar -C ${shellQuote(pathParent(runtimeVaultPath))} -czf \"\$TARGET_DIR/vault.tar.gz\" ${shellQuote(pathBase(runtimeVaultPath))}",
        "tar -C ${shellQuote(pathParent(dataDir))} -czf \"\$TARGET_DIR/data-dir.tar.gz\" ${shellQuote(pathBase(dataDir))}",
        "",
        "cat <<EOF > \"\$TARGET_DIR/RESTORE.txt\"",
        "Restore steps:",
        "1. Stop the Noterious server.",
        "2. Restore vault.tar.gz so this path exists again: $runtimeVaultPath",
        "3. Restore data-dir.tar.gz so this path exists again: $dataDir",
        "4. Start the server again.",
        "",
        "Notes:",
        "- SQLite index path: $database",
        "- The SQLite index is rebuildable if needed.",
        "- History, trash, custom themes, auth state, and other server-managed files live under the data dir.",
        "EOF",
        "",
        "printf '%s\\n' \"Backup written to \$TARGET_DIR\"",
        "printf '%s\\n' \"Created: vault.tar.gz, data-dir.tar.gz, RESTORE.txt\"",
    )
    return lines.joinToString("\n") + "\n"
}

private fun safeString(value: String?, fallback: String = ""): String {
    return value?.trim().takeUnless { it.isNullOrBlank() } ?: fallback
}

private fun safeTimestamp(value: String): String {
    return safeString(value, Instant.now().toString()).replace(":", "-")
}

private fun shellQuote(value: String): String {
    return "'" + value.replace("'", "'\"'\"'") + "'"
}

private fun pathParent(path: String): String {
    val trimmed = path.trim().trimEnd('/')
    if (trimmed.isBlank()) {
        return "."
    }
    val index = trimmed.lastIndexOf('/')
    return when {
        index < 0 -> "."
        index == 0 -> "/"
        else -> trimmed.substring(0, index)
    }
}

private fun pathBase(path: String): String {
    val trimmed = path.trim().trimEnd('/')
    if (trimmed.isBlank()) {
        return "."
    }
    val index = trimmed.lastIndexOf('/')
    return if (index < 0) trimmed else trimmed.substring(index + 1)
}

private fun comment(value: String): String {
    return "# " + value.trim().replace(Regex("\\s+"), " ")
}
